name: NPM Publish

on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install Rust and Wasm-pack
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        rustup target add wasm32-unknown-unknown
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build the wasm package
      run: wasm-pack build --target web 
    - name: Publish to NPM
      run: cd pkg && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
